import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { CategoryFilterBar, FilterSearchInput, HomeFooter, HomeHeader, HomeTitle, ProductCard } from '@/components'
import { Product } from '@/models'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [productsList, setProductsList] = useState([])

  useEffect(() => {
    const fetchProducts = async () => {
      const productsData = await fetch('api/productsList')
      const { products } = await productsData.json()
      setProductsList(products.map((product: { id: number; brand: string; skus: any; image: string, origin: string, information: string }) => Product.fromJson(product)))
    }

    try {
      fetchProducts()
    } catch (e) {
      console.log(e)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomeHeader />
        <HomeTitle />
        <FilterSearchInput />
        <CategoryFilterBar />
        <div className={styles.productList}>
          {productsList.map(({ id, brand, defaultSku, imageUrl }) => {
            return <ProductCard key={id} productId={id} sku={defaultSku} brand={brand} imageUrl={imageUrl} />
          })}
        </div>
        <HomeFooter />
      </main>
    </>
  )
}
